name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }} 
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }} 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make
     
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    rules:
      - if: $CI_COMMIT_BRANCH
    steps:
      - run: check.sh $(pwd) $(pwd)
      - run: |
          file="coding-style-reportslog"
          while IFS= read -r line; do
            offending_file="$(echo "$line" | grep -oP '.+(?=:[0-9]+:)' | cut -c 3-)"
            offending_line="$(echo "$line" | grep -oP '(?!\..+:)[0-9]+(?=:)')"
            error_level="$(echo "$line" | grep -oE "(MAJOR|MINOR|INFO)")"
            error_type="$(echo "$line" | grep -oP "C-[A-Z]+[0-9]+$")"
            echo "Ligne lue : $line"
          done < "$file"