name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }} 
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }} 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make
     
  check_coding_style:
    image: ghcr.io/epitech/coding-style-checker:latest
    script:
      - check.sh $(pwd) $(pwd)
    rules:
      - if: $CI_COMMIT_BRANCH
    allow_failure: true
    tags:
      - docker
    artifacts:
      paths:
        - gl-code-quality-report.json
    script:
      - sh check.sh $(pwd) $(pwd) || (echo "Coding style errors found" && exit 1)
    artifacts:
      reports:
        codequality: gl-code-quality-report.json
